  [[main]]
  name = "Blog"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Bio"
  weight = 300
  identifier = "about"
  url = "/about/"
  
  [[main]]
  name = "CV - English"
  weight = 400
  identifier = "cv"
  url = "/CV.pdf"
  
  [[main]]
  name = "CV - Français"
  weight = 500
  identifier = "cv_fr"
  url = "/CV_Francais.pdf"
